In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn.linear_model as lm
import pickle
from sklearn.externals import joblib

In [32]:
df=pd.read_csv("Fuelcons.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [33]:
df.describe()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [34]:
value=np.random.rand(len(df))<.8
train=df[value]
test=df[~value]

In [35]:
print(train)

      MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4
1          2014  ACURA         ILX         COMPACT         2.4          4
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6
5          2014  ACURA         RLX        MID-SIZE         3.5          6
...         ...    ...         ...             ...         ...        ...
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7
1              M6        Z                  11.2                  7.7
2             AV7        Z                   6.0                  5.8
3             AS6        Z                  12.7                  9.1
5             AS6        Z                  11.9                  7.7
...           ...      ...                   ...                  ...
1062          AS6        X                  13.4                  9.8
1063          AS6        X                  13.2                  9.5
1064          AS6        X                  13.4                  9.8
1065          AS6        X                  12.9                  9.3
1066          AS6        X                  14.9                 10.2

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
0                      8.5                        33           196
1                      9.6                        29           221
2                      5.9                        48           136
3                     11.1                        25           255
5                     10.0                        28           230
...                    ...                       ...           ...
1062                  11.8                        24           271
1063                  11.5                        25           264
1064                  11.8                        24           271
1065                  11.3                        25           260
1066                  12.8                        22           294

[847 rows x 13 columns]

In [36]:
print(test)

      MODELYEAR        MAKE                     MODEL    VEHICLECLASS  \
4          2014       ACURA                   RDX AWD     SUV - SMALL
7          2014       ACURA                    TL AWD        MID-SIZE
10         2014       ACURA                       TSX         COMPACT
19         2014        AUDI                        A4         COMPACT
20         2014        AUDI                A4 QUATTRO         COMPACT
...         ...         ...                       ...             ...
1038       2014  VOLKSWAGEN                 JETTA GLI         COMPACT
1041       2014  VOLKSWAGEN    JETTA TDI CLEAN DIESEL         COMPACT
1042       2014  VOLKSWAGEN        JETTA TURBO HYBRID         COMPACT
1050       2014  VOLKSWAGEN                    ROUTAN         MINIVAN
1055       2014  VOLKSWAGEN  TOUAREG TDI CLEAN DIESEL  SUV - STANDARD

      ENGINESIZE  CYLINDERS TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  \
4            3.5          6          AS6        Z                  12.1
7            3.7          6          AS6        Z                  12.8
10           2.4          4           M6        Z                  11.2
19           2.0          4          AV8        Z                   9.9
20           2.0          4          AS8        Z                  11.5
...          ...        ...          ...      ...                   ...
1038         2.0          4           A6        Z                  10.2
1041         2.0          4           M6        D                   7.9
1042         1.4          4          AM7        Z                   5.6
1050         3.6          6           A6        X                  14.2
1055         3.0          6          AS8        D                  12.3

      FUELCONSUMPTION_HWY  FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  \
4                     8.7                  10.6                        27
7                     9.0                  11.1                        25
10                    8.1                   9.8                        29
19                    7.4                   8.8                        32
20                    8.1                  10.0                        28
...                   ...                   ...                       ...
1038                  7.5                   9.0                        31
1041                  5.6                   6.9                        41
1042                  5.2                   5.4                        52
1050                  9.5                  12.1                        23
1055                  8.0                  10.4                        27

      CO2EMISSIONS
4              244
7              255
10             225
19             202
20             230
...            ...
1038           207
1041           186
1042           124
1050           278
1055           281

[220 rows x 13 columns]

In [37]:
regr=lm.LinearRegression()
train_x=np.asanyarray(train[["ENGINESIZE","CYLINDERS"]])
train_y=np.asanyarray(train[["CO2EMISSIONS"]])
regr.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
print(regr.coef_)

[[26.92269861 10.70107078]]

In [39]:
print(regr.intercept_)

[105.09112152]

In [40]:
#Saving the model
joblib.dump(regr,"fuelconsumption.pkl")

['fuelconsumption.pkl']

In [41]:
test_x=np.asanyarray(test[["ENGINESIZE","CYLINDERS"]])
test_y=np.asanyarray(test[["CO2EMISSIONS"]])
prediction=regr.predict(test_x)
print(prediction)
predict.show()

[[263.52699134]
 [268.91153106]
 [212.50988131]
 [201.74080186]
 [201.74080186]
 [250.06564204]
 [403.11697214]
 [201.74080186]
 [250.06564204]
 [303.77502193]
 [250.06564204]
 [298.39048221]
 [201.74080186]
 [395.04016255]
 [395.04016255]
 [201.74080186]
 [201.74080186]
 [201.74080186]
 [250.06564204]
 [309.15956165]
 [309.15956165]
 [309.15956165]
 [201.74080186]
 [250.06564204]
 [250.06564204]
 [201.74080186]
 [250.06564204]
 [250.06564204]
 [201.74080186]
 [201.74080186]
 [212.50988131]
 [201.74080186]
 [201.74080186]
 [357.62041916]
 [357.62041916]
 [357.62041916]
 [196.35626214]
 [212.50988131]
 [266.2192612 ]
 [212.50988131]
 [352.23587943]
 [201.74080186]
 [333.3899904 ]
 [357.62041916]
 [333.3899904 ]
 [185.5871827 ]
 [185.5871827 ]
 [196.35626214]
 [185.5871827 ]
 [266.2192612 ]
 [266.2192612 ]
 [212.50988131]
 [344.15906985]
 [266.2192612 ]
 [344.15906985]
 [266.2192612 ]
 [266.2192612 ]
 [344.15906985]
 [266.2192612 ]
 [344.15906985]
 [266.2192612 ]
 [266.2192612 ]
 [266.2192612 ]
 [266.2192612 ]
 [212.50988131]
 [212.50988131]
 [185.5871827 ]
 [266.2192612 ]
 [185.5871827 ]
 [185.5871827 ]
 [185.5871827 ]
 [185.5871827 ]
 [190.97172242]
 [201.74080186]
 [263.52699134]
 [263.52699134]
 [357.62041916]
 [268.91153106]
 [268.91153106]
 [325.31318082]
 [325.31318082]
 [268.91153106]
 [268.91153106]
 [190.97172242]
 [263.52699134]
 [201.74080186]
 [201.74080186]
 [201.74080186]
 [188.27945256]
 [333.3899904 ]
 [333.3899904 ]
 [266.2192612 ]
 [212.50988131]
 [263.52699134]
 [201.74080186]
 [212.50988131]
 [188.27945256]
 [263.52699134]
 [263.52699134]
 [201.74080186]
 [258.14245162]
 [212.50988131]
 [212.50988131]
 [212.50988131]
 [190.97172242]
 [263.52699134]
 [268.91153106]
 [325.31318082]
 [250.06564204]
 [250.06564204]
 [325.31318082]
 [325.31318082]
 [325.31318082]
 [212.50988131]
 [212.50988131]
 [344.15906985]
 [266.2192612 ]
 [212.50988131]
 [190.97172242]
 [201.74080186]
 [201.74080186]
 [201.74080186]
 [190.97172242]
 [201.74080186]
 [258.14245162]
 [201.74080186]
 [408.50151186]
 [325.31318082]
 [325.31318082]
 [196.35626214]
 [236.60429273]
 [236.60429273]
 [263.52699134]
 [314.54410138]
 [314.54410138]
 [325.31318082]
 [268.91153106]
 [268.91153106]
 [336.08226027]
 [293.00594249]
 [201.74080186]
 [201.74080186]
 [268.91153106]
 [188.27945256]
 [215.20215117]
 [201.74080186]
 [201.74080186]
 [215.20215117]
 [201.74080186]
 [263.52699134]
 [263.52699134]
 [263.52699134]
 [338.77453013]
 [204.43307172]
 [263.52699134]
 [263.52699134]
 [263.52699134]
 [317.23637124]
 [338.77453013]
 [338.77453013]
 [204.43307172]
 [263.52699134]
 [317.23637124]
 [317.23637124]
 [352.23587943]
 [263.52699134]
 [338.77453013]
 [357.62041916]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [190.97172242]
 [201.74080186]
 [212.50988131]
 [201.74080186]
 [215.20215117]
 [215.20215117]
 [190.97172242]
 [263.52699134]
 [201.74080186]
 [263.52699134]
 [260.83472148]
 [266.2192612 ]
 [266.2192612 ]
 [319.9286411 ]
 [266.2192612 ]
 [411.19378172]
 [212.50988131]
 [201.74080186]
 [201.74080186]
 [215.20215117]
 [201.74080186]
 [201.74080186]
 [263.52699134]
 [196.35626214]
 [263.52699134]
 [196.35626214]
 [215.20215117]
 [220.58669089]
 [276.98834065]
 [276.98834065]
 [196.35626214]
 [201.74080186]
 [201.74080186]
 [201.74080186]
 [225.90322195]
 [201.74080186]
 [201.74080186]
 [201.74080186]
 [201.74080186]
 [201.74080186]
 [185.5871827 ]
 [266.2192612 ]
 [250.06564204]]

NameError: name 'predict' is not defined

In [47]:
predict_df=pd.read_csv("find.csv")
predict_df.head()

   ENGINESIZE  CYLINDERS  CO2EMISSIONS
0         3.2        5.8             0

In [48]:
predict_x=np.asanyarray(predict_df[["ENGINESIZE","CYLINDERS"]])
prediction=regr.predict(predict_x)
print(prediction)

[[253.3099676]]